/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar
import io.papermc.paperweight.userdev.PaperweightUser
import io.papermc.paperweight.tasks.RemapJar

// plugin versioning
version = "0.0.4"

// base of output jar name
val OUTPUT_JAR_NAME = "bc"

// target will be set to minecraft version by cli input parameter
var target = ""

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm")
    id("com.github.johnrengelman.shadow")
    // maven() // no longer needed in gradle 7
    
    // include paperweight, but DO NOT APPLY BY DEFAULT...
    // we need imports, but only conditionally apply it for 1.17+ builds
    // for 1.16.5, we don't want to apply because not supported, it
    // does not allow building unless a bundle version is applied,
    // which does not exist for 1.16.5, so its impossible to build with
    // paperweight plugin enabled on 1.16.5
    // https://stackoverflow.com/questions/62579114/how-to-optionally-apply-some-plugins-using-kotlin-dsl-and-plugins-block-with-gra

    // i fucking hate gradle and cant configure this
    // just manually uncomment

    // USE FOR 1.16.5, UNCOMMENT WHEN NEEDED :^(
    // id("io.papermc.paperweight.userdev") version "1.3.8" apply false
    
    // USE FOR 1.18.2 (DEFAULT)
    id("io.papermc.paperweight.userdev")
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
    
    maven { // paper
        url = uri("https://papermc.io/repo/repository/maven-public/")
    }
    maven { // worldguard
        url = uri("https://maven.enginehub.org/repo/")
    }
}

configurations {
    create("resolvableImplementation") {
        isCanBeResolved = true
        isCanBeConsumed = true
    }

    // Special configuration with priority over compileOnly.
    // Required so we can include NMS and bukkit as dependency,
    // without overriding the paper API (which has slight differences
    // in api). See:
    // https://github.com/gradle/gradle/issues/10502
    // https://stackoverflow.com/questions/31698510/can-i-force-the-order-of-dependencies-in-my-classpath-with-gradle/47953373#47953373
    create("compileOnlyPriority") {
        isCanBeResolved = true
        isCanBeConsumed = true
        sourceSets["main"].compileClasspath = configurations["compileOnlyPriority"] + sourceSets["main"].compileClasspath
    }
}


dependencies {
    // Align versions of all Kotlin components
    compileOnly(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Kotlin runtime - compileOnly for building, resolvableImplementation for shadow jar
    compileOnly("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    configurations["resolvableImplementation"]("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // Kotlin reflect api
    compileOnly("org.jetbrains.kotlin:kotlin-reflect")
    configurations["resolvableImplementation"]("org.jetbrains.kotlin:kotlin-reflect")

    // toml parsing library
    compileOnly("org.tomlj:tomlj:1.1.0")
    configurations["resolvableImplementation"]("org.tomlj:tomlj:1.1.0")

    // world guard region protection
    compileOnly("com.sk89q.worldguard:worldguard-bukkit:7.0.7")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")

    // MINECRAFT VERSION SPECIFIC BUILD CONFIGURATION
    if (project.hasProperty("1.16") == true) {
        java.toolchain.languageVersion.set(JavaLanguageVersion.of(16))
        sourceSets["main"].java.srcDir("src/nms/v1_16_R3")
        compileOnly(files("./lib/spigot-1.16.5.jar"))
        configurations["compileOnlyPriority"]("com.destroystokyo.paper:paper-api:1.16.5-R0.1-SNAPSHOT")
        target = "1.16.5"
    } else {
        java.toolchain.languageVersion.set(JavaLanguageVersion.of(21))
        sourceSets["main"].java.srcDir("src/nms/v1_21_R4")

        paperweight.paperDevBundle("1.21.5-R0.1-SNAPSHOT")
        compileOnly("io.papermc.paper:paper-api:1.21.5-R0.1-SNAPSHOT")

        target = "1.21.5"
    }
}

tasks.withType<KotlinCompile> {
    kotlinOptions.freeCompilerArgs = listOf("-Xallow-result-return-type")
}

tasks {
    named<ShadowJar>("shadowJar") {
        // verify valid target minecraft version
        doFirst {
            val supportedMinecraftVersions = setOf("1.16.5", "1.18.2", "1.21.5")
            if ( !supportedMinecraftVersions.contains(target) ) {
                throw Exception("Invalid Minecraft version! Supported versions are: 1.16, 1.18")
            }
        }

        archiveClassifier.set("all")
        configurations = mutableListOf(project.configurations.named("resolvableImplementation").get()) as List<FileCollection>
    }
}

tasks {
    build {
        dependsOn(shadowJar)
    }
    
    test {
        testLogging.showStandardStreams = true
    }
}

gradle.taskGraph.whenReady {
    tasks {
        named<ShadowJar>("shadowJar") {
            archiveBaseName.set("${OUTPUT_JAR_NAME}-${target}-SNAPSHOT")
            // minimize()
        }
    }
}
